### ISSUE TITLE
Introduce \SolidLine{...}

### ISSUE THREAD

**Issue by TrackerSB** [rolfn/leaflet#2]
Similar to `\CutLine{...}` there could be a macro which allows to insert a solid line between the pages.

**Comment by rolfn** [comment]
I added an optional parameter to the `\CutLine` macro. You can write now
```
\CutLine[-]{6}
```
for a solid line between page 5 and 6 (`-` symbolizes the solid line). Good?

**Comment by TrackerSB** [comment]
That's an even better idea than creating another macro. 👍 
Thank you.

**Comment by rolfn** [comment]
The new version is now on the way to CTAN.
