### ISSUE TITLE
page number on page 1

### ISSUE THREAD

**Issue by henk84** [rolfn/leaflet#3]
Hi

Even with the simplest document I still get a page number on the bottom of the first page.
I normally use `lualatex` but tested and it also happens with `pdflatex`.
Am I doing anything wrong?
Is that intended?
How do I get rid of the page number?

```
\documentclass{leaflet}

\begin{document}
\title{John Doe}
\date{}
\maketitle

\end{document}
```

Thank you!

**Comment by rolfn** [comment]
Change the page style of the front page as follows:

```
\documentclass{leaflet}

\begin{document}
\title{John Doe}
\date{}
\maketitle
\thispagestyle{empty}

\end{document}
```

You can also find this in the example file `leaflet-manual.tex`. In special cases, a real page style could also be useful, but this may require changes to the page geometry.

**Comment by henk84** [comment]
Hi, thank you very much for the quick response!

> Change the page style of the front page as follows:
> 
> ```
> \documentclass{leaflet}
> 
> \begin{document}
> \title{John Doe}
> \date{}
> \maketitle
> \thispagestyle{empty}
> 
> \end{document}
> ```
> 
> You can also find this in the example file `leaflet-manual.tex`. In special cases, a real page style could also be useful, but this may require changes to the page geometry.

Tried it and it works.

I do have to say, though, that I still consider this bug "not resolved". The manual says:

> By default, there are no page headers, page footers or page numbers, nor is there any space reserved for these.

As it is, the statement is not quite reflecting how the class currently works. It also does not mention that one needs to use `\thispagestyle{empty}` to also have no page number on page 1.
So IMHO either it should not happen, i.e. the class should already take care of this so the statement is actually true, or the manual should say that this needs to be done.

Furthermore, while trying to find the `leaflet-manual.tex` file, I noticed that this file is not available in this git repository and also not linked on https://ctan.org/pkg/leaflet.
So I don’t think users should be expected to read _the source_ to the manual, as opposed to just "reading the manual" to figure this out.

Please consider my suggestions for improving this situation. It might help others avoid this issue, make the class easier to use, and avoid similar questions in the future.

I appreciate your effort providing this class and especially the quick response to this issue, thank you very much!

**Comment by rolfn** [comment]
Ok, I agree. The cause of the problem is that `\maketitle` sets the page style to "plain". I have now changed this in version 2.1c so that the title page, like all other pages, has the page style "empty". `\thispagestyle{empty}` is no longer necessary.

The new version will appear on CTAN shortly.
